### ISSUE TITLE
Get rid of *_t suffixes in the naming convention

### ISSUE THREAD

**Issue by cher-nov** [cher-nov/Gena#13]
https://github.com/cher-nov/Gena/commit/8ff8c87989e224656108438b05a8f805c70ce6b9#r27154367

They're also reserved identifiers, see
http://www.gnu.org/software/libc/manual/html_node/Reserved-Names.html
> - Names that end with ‘_t’ are reserved for additional type names.

**Comment by cher-nov** [comment]
Fixed by d921f2822e9307a2a1c065e90d2ba20d2f727788.

**Comment by rofl0r** [comment]
wow, that diff is much larger than anticipated o.0
